version: '3'
services:
  dashy:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./user-data:/app/public/user-data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
